services:
  mailpit:
    image: mailpit/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
  
  postgres:
    container_name: field-up-db
    image: postgres:16
    environment:
      POSTGRES_DB: fieldup_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    container_name: localstack
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - LS_LOG=info
    volumes:
      - ./.localstack:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data: 
